timeout: 3

/SonnaOS (Estella kernel)
    protocol: limine
    
    path: boot():/boot/estella.elf

    module_path: boot():/boot/spleen/spleen-12x24.psfu
    module_string: spleen-12x24

    module_path: boot():/boot/task_a.elf
    module_string: task_a

    module_path: boot():/boot/task_b.elf
    module_string: task_b

    module_path: boot():/boot/task_c.elf
    module_string: task_c

    module_path: boot():/boot/logo.raw
    module_string: logo_raw